services:
  - type: web
    name: classsync-backend
    runtime: docker # Changed from java to docker
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: SPRING_MAIL_USERNAME
        value: t51092567@gmail.com
      - key: SPRING_MAIL_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CANVAS_API_TOKEN
        sync: false
      - key: CANVAS_API_BASE_URL
        value: ://instructure.com
